define([], function () {
  return {
    // audioNode: 'AudioNode',
    // audioParam: 'AudioParam',
    // audioProcessingEvent: 'AudioProcessingEvent',
    // offlineAudioCompletionEvent: 'OfflineAudioCompletionEvent',
    analyser: 'AnalyserNode',
    audioBuffer: 'AudioBuffer',
    audioBufferSource: 'AudioBufferSourceNode',
    audioContext: 'AudioContext',
    audioDestination: 'AudioDestinationNode',
    audioListener: 'AudioListener',
    biquadFilter: 'BiquadFilterNode',
    channelMerger: 'ChannelMergerNode',
    channelSplitter: 'ChannelSplitterNode',
    constantSource: 'ConstantSourceNode',
    convolver: 'ConvolverNode',
    delay: 'DelayNode',
    dynamicsCompressor: 'DynamicsCompressorNode',
    gain: 'GainNode',
    IIRFilter: 'IIRFilterNode',
    mediaElementAudioSource: 'MediaElementAudioSourceNode',
    mediaStreamAudioDestination: 'MediaStreamAudioDestinationNode',
    mediaStreamAudioSource: 'MediaStreamAudioSourceNode',
    offlineAudioContext: 'OfflineAudioContext',
    oscillator: 'OscillatorNode',
    panner: 'PannerNode',
    periodicWave: 'PeriodicWave',
    stereoPanner: 'StereoPannerNode',
    waveShaper: 'WaveShaperNode',

    compressor: 'DynamicsCompressorNode',
    filter: 'BiquadFilterNode',
    iir: 'IIRFilterNode',
    merger: 'ChannelMergerNode',
    shaper: 'WaveShaperNode',
    splitter: 'ChannelSplitterNode',
  };
})
